version: '3.8'

services:
  # 1. 기존 장고 웹 서비스 (SQLite 그대로 사용)
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  # 2. 새로 추가할 Redis 서비스
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"